title: Smart Waste Management System
description: A Smart Waste Management System streamlines waste collection, recycling, and composting using technology to enhance efficiency and sustainability.
theme: jekyll-theme-cayman
